services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: parking_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: abc123
      DB_NAME: parking_db
      DB_HOST: db
      JWT_SECRET: 0102030405060708090a0b0c0d0e0f
      PORT: 5000
    ports:
      - "5000:5000"

volumes:
  pgdata: